export const modules = [
  {
    id: "core-rh",
    name: "Core RH",
    description: "Colaboradores, puestos, áreas y estructura base",
    href: "/core-rh",
    color: "bg-blue-600",
    tables: ["Colaborador", "Puesto", "Área", "Departamento", "Sede", "Centro de costo", "Relación laboral"],
  },
  {
    id: "organizacion",
    name: "Organización",
    description: "Organigrama y movimientos organizacionales",
    href: "/organizacion",
    color: "bg-indigo-600",
    tables: ["Organigrama", "Posición", "Vacante", "Movimiento organizacional"],
  },
  {
    id: "vacaciones",
    name: "Vacaciones / Permisos",
    description: "Solicitudes, saldos y calendarios laborales",
    href: "/vacaciones",
    color: "bg-emerald-600",
    tables: ["Política", "Saldo", "Solicitud", "Tipo de ausencia", "Calendario laboral", "Días inhábiles", "Aprobación"],
  },
  {
    id: "requisiciones",
    name: "Requisiciones",
    description: "Requisiciones de personal y aprobaciones",
    href: "/requisiciones",
    color: "bg-amber-600",
    tables: ["Requisición de personal", "Justificación", "Presupuesto", "Perfil", "Aprobadores", "Historial"],
  },
  {
    id: "reclutamiento",
    name: "Reclutamiento",
    description: "Vacantes, candidatos y proceso de selección",
    href: "/reclutamiento",
    color: "bg-violet-600",
    tables: ["Vacante", "Publicación", "Candidato", "Postulación", "CV", "Entrevista", "Evaluación", "Oferta"],
  },
  {
    id: "onboarding",
    name: "Onboarding",
    description: "Planes de integración y tareas",
    href: "/onboarding",
    color: "bg-cyan-600",
    tables: ["Plan onboarding", "Tarea onboarding", "Responsable", "Evidencia", "Checklist", "Fecha compromiso"],
  },
  {
    id: "documentos",
    name: "Documentos",
    description: "Expedientes y gestión documental",
    href: "/documentos",
    color: "bg-slate-600",
    tables: ["Expediente", "Documento", "Tipo documento", "Vigencia", "Firma", "Versión", "Confidencialidad"],
  },
  {
    id: "desempeno",
    name: "Desempeño",
    description: "Ciclos, objetivos y evaluaciones",
    href: "/desempeno",
    color: "bg-rose-600",
    tables: ["Ciclo", "Objetivo", "Competencia", "Evaluación", "Feedback", "Resultado"],
  },
  {
    id: "capacitacion",
    name: "Capacitación",
    description: "Cursos, inscripciones y constancias",
    href: "/capacitacion",
    color: "bg-orange-600",
    tables: ["Curso", "Inscripción", "Evidencia", "Evaluación", "Constancia"],
  },
  {
    id: "beneficios",
    name: "Beneficios",
    description: "Catálogo de beneficios y solicitudes",
    href: "/beneficios",
    color: "bg-teal-600",
    tables: ["Beneficio", "Solicitud beneficio", "Elegibilidad", "Aprobación"],
  },
  {
    id: "auditoria",
    name: "Auditoría",
    description: "Bitácora, integraciones y trazabilidad",
    href: "/auditoria",
    color: "bg-zinc-700",
    tables: ["Bitácora evento", "Cambio estado", "Notificación enviada", "Integración", "Error integración"],
  },
] as const;

export type ModuleId = (typeof modules)[number]["id"];
